#include <stdio.h>

#define MAX 100
/*
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*/
int sum;

int fibonacci(int n);

int fibonacci(int n){
  if(n == 0)
    return 0;
  else if(n == 1)
    return 1;
  else
    /*printf("%d, ", (fibonacci(n-1) + fibonacci(n-2))); */
    return (fibonacci(n-1) + fibonacci(n-2));
}

int main(){
  int i, x;

  sum = 0;
  x = 0;
  for(i = 1; i < 100; ++i){
    int fib;
    printf("%d : F-%d\n", fib=fibonacci(x), i);
    if(fib%2 == 0 && fib > 0){
      printf("Even detected, stuffing %d into sum\n\n", fib);
      sum += fib;
    }
    else if(fib >= 4000000){
      break;
    }
    ++x;
  }
  printf("\nSum: %d\n", sum); 
  printf("\n");

  return 0;
}